### ISSUE TITLE
ValueError: Layer model expects 1 input(s), but it received 2 input tensors.

### ISSUE THREAD

**Issue by GaoTiaoKang** [diogenes0319/FedMD_clean#2] opened 2021-05-05 08:56 UTC

**Comment by zhanghui-svg** [comment] 2021-06-01 01:07
Have you solved this problem？

**Comment by diogenes0319** [comment] 2021-06-03 05:04
Hello,  sorry for the slow reply. 

Please see https://github.com/diogenes0319/FedMD_clean/issues/3 for the cause of the bug and the solution.  
I will close this issue as it is duplicated to issue #3.

**Closed as completed** 2021-06-03 05:05 UTC
